something
aberikashvili/thc-angular pull request #33
Opened 2023-05-12 20:40 UTC by koksoni

2023-05-27 19:12 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.scss
> +        // }
წაშალე

2023-05-27 19:12 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.scss
> +    // margin-top: 69px;
წაშალე

2023-05-27 19:16 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.scss
> +                  &--image{
დოკუმენტის ფორმატირება გაასწორე.

1. VSCode-ში, დააჭირე extensioins
2. ძიებაში ჩაწერე `@recommended`
3. დააინსტალირე ოთხივე ექსთენშენი
4. ამის შემდეგ გახსენი `news-page.component.scss` ფაილი და დააჭირე `Ctrl + S`, ფორმატირება ავტომატურად გასწორდება

![image](https://github.com/aberikashvili/thc-angular/assets/3863691/c95be287-1340-40c9-bbbd-d26a19527c93)

2023-05-27 19:16 UTC, koksoni commented on src/app/modules/news/components/news-page/news-page.component.scss
> +        // }
done

2023-05-27 19:16 UTC, aberikashvili commented on src/app/modules/news/news.component.html
> +   -->
წაშალე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/app-routing.module.ts
ფორმატირება გაასწორე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/app.module.ts
ფორმატირება გაასწორე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.html
ფორმატირება გაასწორე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.scss
ფორმატირება გაასწორე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/modules/news/components/news-page/news-page.component.ts
ფორმატირება გაასწორე

2023-06-11 21:00 UTC, aberikashvili commented on src/app/modules/news/news.module.ts
ფორმატირება გაასწორე

2023-06-11 21:01 UTC, aberikashvili commented on src/app/shared/components/footer/footer.component.html
ფორმატირება გაასწორე

2023-06-11 21:01 UTC, aberikashvili commented on src/app/shared/shared.module.ts
ფორმატირება გაასწორე

2023-06-11 21:02 UTC, aberikashvili requested changes
კოდის ფორმატირება გაასწორე და rebase გაუკეთე

2023-06-12 08:57 UTC, aberikashvili approved these changes

2023-06-12 08:58 UTC, merged